version: "3.9"
services:
    db:
        image: "mcr.microsoft.com/mssql/server:2019-latest"
        environment:
            SA_PASSWORD: "Pa55word1"
            ACCEPT_EULA: "Y"
            MSQL_PID: Express
        ports:
          - "1433:1433"
    web:
      build: .
      ports:
          - "8090:80"
      depends_on:
          - db